/**
 * PDF Generation Utility for Legal Documents
 *
 * Generates professional PDF files from legal document text
 * with proper formatting for Indian legal documents
 */

import jsPDF from 'jspdf';

export interface PDFOptions {
  title: string;
  content: string;
  documentType: string;
  createdDate: Date;
}

/**
 * Generate PDF from legal document content
 */
export function generatePDF(options: PDFOptions): void {
  const { title, content, documentType, createdDate } = options;

  // Create new PDF document (A4 size)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Page dimensions
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20; // 20mm margins
  const contentWidth = pageWidth - (margin * 2);

  // Colors
  const primaryColor: [number, number, number] = [0, 0, 0]; // Black
  const secondaryColor: [number, number, number] = [100, 100, 100]; // Gray

  let yPosition = margin;

  // Helper function to add page if needed
  const checkPageBreak = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Header section with document metadata
  doc.setFontSize(8);
  doc.setTextColor(...secondaryColor);
  doc.text('Generated by Lekhai', margin, yPosition);
  doc.text(
    new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric'
    }),
    pageWidth - margin,
    yPosition,
    { align: 'right' }
  );
  yPosition += 10;

  // Title
  doc.setFontSize(16);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(title, contentWidth);
  doc.text(titleLines, margin, yPosition);
  yPosition += titleLines.length * 7 + 5;

  // Document type and date
  doc.setFontSize(10);
  doc.setTextColor(...secondaryColor);
  doc.setFont('helvetica', 'normal');
  doc.text(`Type: ${documentType.replace(/_/g, ' ')}`, margin, yPosition);
  yPosition += 5;
  doc.text(
    `Created: ${new Date(createdDate).toLocaleDateString('en-IN')}`,
    margin,
    yPosition
  );
  yPosition += 10;

  // Divider line
  doc.setDrawColor(...secondaryColor);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Content
  doc.setFontSize(11);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'normal');

  // Split content into lines and paragraphs
  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Handle empty lines (paragraph breaks)
    if (line.trim() === '') {
      yPosition += 4;
      checkPageBreak(10);
      continue;
    }

    // Check if line looks like a heading (all caps, short, or starts with specific patterns)
    const isHeading =
      (line === line.toUpperCase() && line.length < 50) ||
      line.match(/^(TO:|FROM:|SUBJECT:|AFFIDAVIT|LEGAL NOTICE|RENT RECEIPT)/i);

    if (isHeading) {
      checkPageBreak(15);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
    }

    // Split long lines to fit page width
    const wrappedLines = doc.splitTextToSize(line, contentWidth);

    for (const wrappedLine of wrappedLines) {
      checkPageBreak(7);
      doc.text(wrappedLine, margin, yPosition);
      yPosition += 6;
    }

    // Extra spacing after headings
    if (isHeading) {
      yPosition += 3;
    }
  }

  // Footer on each page
  const pageCount = doc.internal.pages.length - 1; // Exclude first empty page
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...secondaryColor);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'This is a computer-generated legal document',
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }

  // Generate filename from title
  const filename = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`;

  // Save the PDF
  doc.save(filename);
}

/**
 * Generate print-optimized PDF (for notary/legal use)
 */
export function generateNotaryPDF(options: PDFOptions): void {
  const { title, content, documentType, createdDate } = options;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25; // Larger margins for notary use
  const contentWidth = pageWidth - (margin * 2);

  let yPosition = margin;

  const checkPageBreak = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin - 30) { // Extra space for signatures
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Content only (minimal metadata for official use)
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont('times', 'normal'); // Times New Roman for formal documents

  const lines = content.split('\n');

  for (const line of lines) {
    if (line.trim() === '') {
      yPosition += 5;
      checkPageBreak(10);
      continue;
    }

    const isHeading = line === line.toUpperCase() && line.length < 50;

    if (isHeading) {
      checkPageBreak(15);
      doc.setFont('times', 'bold');
      doc.setFontSize(14);
    } else {
      doc.setFont('times', 'normal');
      doc.setFontSize(12);
    }

    const wrappedLines = doc.splitTextToSize(line, contentWidth);

    for (const wrappedLine of wrappedLines) {
      checkPageBreak(8);
      doc.text(wrappedLine, margin, yPosition);
      yPosition += 7;
    }

    if (isHeading) {
      yPosition += 4;
    }
  }

  // Add signature section at the end
  checkPageBreak(40);
  yPosition += 20;

  doc.setFont('times', 'normal');
  doc.setFontSize(10);
  doc.line(margin, yPosition, margin + 50, yPosition);
  yPosition += 5;
  doc.text('Signature', margin, yPosition);
  yPosition += 15;
  doc.line(margin, yPosition, margin + 50, yPosition);
  yPosition += 5;
  doc.text('Date', margin, yPosition);

  // Page numbers
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 15,
      { align: 'center' }
    );
  }

  const filename = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_notary.pdf`;
  doc.save(filename);
}
